"""LLM 模板配置 — 用户从 web 端选择"""
LLM_TEMPLATES = {
    'ark': {
        'name': '🚀 字节豆包 ARK',
        'base_url': 'https://ark.cn-beijing.volces.com/api/v3',
        'default_model': 'ep-xxx (你的接入点ID)',
        'model_options': ['ep-20250601-doubao-pro', 'ep-20250601-doubao-lite', 'ark-code-latest'],
        'docs': 'https://www.volcengine.com/docs/82379',
        'placeholder_key': 'ARK API Key (volcengine.com 控制台获取)',
    },
    'deepseek': {
        'name': '🐬 DeepSeek',
        'base_url': 'https://api.deepseek.com/v1',
        'default_model': 'deepseek-chat',
        'model_options': ['deepseek-chat', 'deepseek-reasoner'],
        'docs': 'https://platform.deepseek.com',
        'placeholder_key': 'sk-xxx',
    },
    'moonshot': {
        'name': '🌙 月之暗面 Kimi',
        'base_url': 'https://api.moonshot.cn/v1',
        'default_model': 'moonshot-v1-32k',
        'model_options': ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
        'docs': 'https://platform.moonshot.cn',
        'placeholder_key': 'sk-xxx',
    },
    'qwen': {
        'name': '🧠 阿里通义千问',
        'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        'default_model': 'qwen-plus',
        'model_options': ['qwen-turbo', 'qwen-plus', 'qwen-max'],
        'docs': 'https://help.aliyun.com/zh/dashscope/',
        'placeholder_key': 'sk-xxx',
    },
    'zhipu': {
        'name': '🔮 智谱 GLM',
        'base_url': 'https://open.bigmodel.cn/api/paas/v4',
        'default_model': 'glm-4-plus',
        'model_options': ['glm-4', 'glm-4-plus', 'glm-4-flash'],
        'docs': 'https://open.bigmodel.cn',
        'placeholder_key': 'xxx.xxx',
    },
    'openai': {
        'name': '🤖 OpenAI',
        'base_url': 'https://api.openai.com/v1',
        'default_model': 'gpt-4o-mini',
        'model_options': ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo'],
        'docs': 'https://platform.openai.com',
        'placeholder_key': 'sk-xxx',
    },
    'custom': {
        'name': '⚙️ 自定义（OpenAI兼容）',
        'base_url': '',
        'default_model': '',
        'model_options': [],
        'docs': '',
        'placeholder_key': 'API Key',
    },
}
